### PR TITLE
Return set entry

### PR DESCRIPTION
**Pull request by jgdumas**
make setEntry return the Element is it setting
(behavior of assignment operators)

### CODE REVIEW

**Comment by bdsaunders** [comment]
This looks fine to me.  We should specify what you are doing, that the return value of A.setEntry(i,j,e) is a reference to e and not to the storage of A.  I am thinking of the packed and sliced representations where references to matrix entries are awkward.

More generally about assignment:  Originally we said ring elements are only default constructible and we had F.assign(), so that the field could participate in assignment.  This has never proved necessary.  I found documentation in element/ that element types should be assignable and also we use operator= widely.  I think we can retire the F.assign function.

What about init (when done pro forma and not for the purpose of setting a particular value)?  Do we have any ring where mul(c,a,b) breaks if c has not been init-ed?  poly rings?

**Comment by jgdumas** [comment]
Hello,
Yes the return value of setEntry(i,j,e) is a indeed a reference to e.

Now for assign, no it is used in many places (at least multi-precision) and '=' should definitely never be used. If it is then it's a bug.

It is the same for init. Multi-precision will potentially break, as well as poly-ring if the elements are not initialized.

**Comment by bdsaunders** [comment]
I am looking at map-sparse.inl where you have put in the return value of a
setEntry.  I see the line
     rowMap_[i][j]=e;
This should be an assign()? There are very many such uses. I'm just double
checking here. I don't object to more rigorous use of assign().

**Comment by bdsaunders** [comment]
And we should remove the specification that element types are assignable.

**Comment by jgdumas** [comment]
Yes, I just added the return, but I agree that "rowMap_[i][j]=e;" should be a field().assign ...

**Comment by ClementPernet** [comment]
Ok, I agree with JG's remarks regarding the use of operator= and assign. This is however another problem to be solved in another issue.
This one seems good to me. Merging.

**Pull request merged**
