### PR TITLE
IntegerDom and ZRing<Integer> are not different anymore

### PR DESCRIPTION
**Pull request by jgdumas**
Needed by Givaro PR#120.

### CODE REVIEW

**Comment by jgdumas** [comment]
no more reconstructRational,
only RartionalRecontrusction now, everywhere.

**Comment by ClementPernet** [comment]
There are still some occurrences of `IntegerDom` in `test-det.C` `test-rational-solver.C` `test-smith-form-binary.C` and `algorithms/det-rational.h`

**Comment by jgdumas** [comment]
Well this is now a just typedef. But it could be removed completely in Givaro too ...

**Comment by Breush** [comment]
@ClementPernet I think it's ok with the `IntegerDom` typedef. Just an alias that preserves compatibility. LGTM

**Comment by Breush** [comment]
As this fixes `master`, I'm merging it.

@ClementPernet If you thinks this needs more cleanup, we'll going to do that in an other branch.

**Pull request merged**
