### PR TITLE
compatibility with refactorization modular

### PR DESCRIPTION
**Pull request by jgdumas**

### CODE REVIEW

**Comment by bgrenet** [comment]
See PR [#69](https://github.com/linbox-team/givaro/pull/64) of Givaro and PR [#169](https://github.com/linbox-team/fflas-ffpack/pull/169) of Linbox.

**Comment by bgrenet** [comment]
For information, result of `make fullcheck`:

`Of 109 tests, 72 passed, 6 failed to compile, 1 failed at runtime,  and 30 were skipped.`

**Comment by ClementPernet** [comment]
Ok: besides the ambiguity with the isZero, that you fixed in 672be20e56bbd2bf0 I confirm everything works on fflas-ffpack and Linbox sides as far as the standard test suites are concerned.
In LinBox, test-fullcheck still raises several issues, which I have hard time understanding:
`test-fibb` raises an exception `ERROR (at fgemm in ../../../fflas-ffpack/fflas/fflas_fgemm.inl:402): 
Precondition not met:F.areEqual(e,beta)
terminate called after throwing an instance of 'std::runtime_error'
  what():  F.areEqual(e,beta)
Abandon
`
gdb indicates that the field `_lp` is uninitialized (has value
```
(gdb) run
Starting program: /local/devel/linbox/tests/.libs/test-fibb 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3601700 (LWP 19000)]
[New Thread 0x7ffff0e00700 (LWP 19001)]
[New Thread 0x7fffee5ff700 (LWP 19002)]


ERROR (at fgemm in ../../../fflas-ffpack/fflas/fflas_fgemm.inl:402): 
Precondition not met:F.areEqual(e,beta)
terminate called after throwing an instance of 'std::runtime_error'
  what():  F.areEqual(e,beta)

Thread 1 "test-fibb" received signal SIGABRT, Aborted.
0x00007ffff647e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) up
#1  0x00007ffff648002a in __GI_abort () at abort.c:89
89	abort.c: Aucun fichier ou dossier de ce type.
(gdb) up
#2  0x00007ffff6dc184d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) up
#3  0x00007ffff6dbf6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) up
#4  0x00007ffff6dbf701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) up
#5  0x00007ffff6dbf919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) up
#6  0x00007ffff795f4c1 in FFLAS::fgemm<Givaro::Modular<double, double, void> > (F=..., ta=FFLAS::FflasNoTrans, 
    tb=FFLAS::FflasNoTrans, m=1, n=4, k=<optimized out>, alpha=100, A=0x6543d8, lda=5, B=0x6543b8, ldb=5, beta=1, C=0x6543e0, 
    ldc=5, H=...) at ../../../fflas-ffpack/fflas/fflas_fgemm.inl:402
402			FFLASFFPACK_check(F.areEqual(e,beta));
(gdb) p F
$1 = (const Givaro::Modular<double, double, void> &) @0x7fffffffde70: {<Givaro::Modular_implem<double, double, unsigned long>> = {<Givaro::FiniteFieldInterface<double>> = {<Givaro::FieldInterface<double>> = {<Givaro::RingInterface<double>> = {
          _vptr.RingInterface = 0x42b888 <vtable for Givaro::Modular<double, double, void>+16>}, <No data fields>}, <Givaro::FiniteInterface<double>> = {_vptr.FiniteInterface = 0x42b998 <vtable for Givaro::Modular<double, double, void>+288>}, <No data fields>}, 
    zero = 0, one = 1, mOne = 100, _p = 4636807660098813952, _pc = 4.9900630229965901e-322}, <No data fields>}
(gdb) 
```
but highest level in the callstack (main of test-fibb.C line 235), the field is displayed as follows:
```
gdb) p F
$2 = {<Givaro::FiniteFieldInterface<double>> = {<Givaro::FieldInterface<double>> = {<Givaro::RingInterface<double>> = {
        _vptr.RingInterface = 0x42b888 <vtable for Givaro::Modular<double, double, void>+16>}, <No data fields>}, <Givaro::FiniteInte
rface<double>> = {_vptr.FiniteInterface = 0x42b998 <vtable for Givaro::Modular<double, double, void>+288>}, <No data fields>},
  zero = 0, one = 1, mOne = 100, _p = 101, _lp = 101}
```
and I can not understand where this _lp field comes from. A grep on givaro's sources says it is in modular-extended, but this field is not being used here.

**Comment by bgrenet** [comment]
`make fullcheck` on my machine yields

```
--------------------------------------------------------------------
Of 106 tests, 91 passed, 0 failed to compile, 5 failed at runtime,  and 10 were skipped.
--------------------------------------------------------------------
```

In particular, `test-fibb` compiles and passes. So I do not know where the error you get comes from. Note that `_lp` was a attribute of `Modular<double>` before my changes, so there may be some things not up-to-date on your side?

The 5 failed at runtime are `test-frobenius-large`, `test-frobenius-small` and `test-invariant-factors` that require an input matrix apparently, `test-ntl-lzz_px` for a division by zero (but I was unable to reproduce the error so far) and `test-smith-form-binary` where a computation is false (but I have not yet been able to understand).

I do not know how I should interpret the skipped items.

**Comment by bgrenet** [comment]
Update on `fullcheck`:

```
--------------------------------------------------------------------
Of 106 tests, 92 passed, 0 failed to compile, 4 failed at runtime,  and 10 were skipped.
--------------------------------------------------------------------
```
The 4 failures are:

- `test-frobenius-large`, `test-frobenius-small`, `test-invariant-factors` that requires an input matrix;
- `test-smith-form-binary` which seems to have a problem: This needs to be investigated. For instance, I do not know whether the same failure happens in `master`. The report is not very helpful...

Additionnaly, I encounter some failures in `test-minpoly`, `test-ntl-lzz_px` and `test-ffpack` that do not occur each time. `test-minpoly` fails once every 8-10 runs, `test-ntl-lzz_px` once every 50-100 runs and `test-ffpack` once every 30-40 runs (experimentally). Again, not yet any idea whether it comes from this branch. The error for `test-ntl-lzz_px` is `zz_PX: division by zero`.

**Pull request merged**
